### ISSUE TITLE
RoleClass should be fixed with 3 attributes

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#1]
When you  generate a Role Class, there should be 3 fixed attributes for now. The combination of these attributes makes the Role Class unique. 
The attributes are, eClassIRDI, eClass Classification and eClass version.
- The generation should be made playing with the other attributes
- We can query the eClass ontology for the same Role Class and add attributes for this RoleClass.

**Comment by omarrana** [comment]
The generation should be made playing with the other attributes
i fixed this part , those attributes are not played.

**Comment by igrangel** [comment]
Please, for the next issue, put a reference to the code where you have solved it. In addition, in the commits you can reference the issue by adding the # and the number of the issue.

**Comment by omarrana** [comment]
```
boolean ignoreAttributes(NamedNodeMap baseElmntAttr) {
        for (int i = 0; i < baseElmntAttr.getLength(); ++i) {
            Node attr = baseElmntAttr.item(i);
            if (attr.getNodeValue().equals("eClassVersion") || attr.getNodeValue().equals("eClassClassificationClass")
                    || attr.getNodeValue().equals("eClassIRDI")) {
                return false;
            }
        }
        return true;
    }

}

```

**Comment by igrangel** [comment]
Please have a look at http://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github or related. The good thing would be to connected with the line of code rather to copy - paste the code.

**Comment by omarrana** [comment]
ok thanks :+1: 
https://github.com/i40-Tools/HeterogeneityGenerator/blob/5adebdbd972d7130af0f0b8a8eac08415fdca101/src/main/java/edu/bonn/HetrogeneityGenerator/xmlGen/GranularityHeterogeneity.java#L123-L135

**Comment by igrangel** [comment]
Is this pointing to an specific commit? So, if in the next commit the line is moved, how this will act? Can you check this please?

**Comment by omarrana** [comment]
yes, i have checked , it points to specific commit even if the code moves to next line.
