### ISSUE TITLE
Gold Standard for Generated files

### ISSUE THREAD

**Issue by omarrana** [i40-Tools/AMLGoldStandardGenerator#16]
So our tool does not generate seed.aml
So if we enlarge our heterogeneity files , seed.aml stays unaffected. 
As our gold Standard generation depends on seed.aml , and the heterogeneity files will be enlarged that would lead to wrong GoldStandard.

How can we tackle this situation.

**Comment by igrangel** [comment]
Every method should have an **input** and an **output**.
So, the **input** of our method can be a file, which already contains some heterogeneity, e.g., **_M2_**.
In this way, we will have the heterogeneities and based on this the generation. 
Next, we should define the _actions_ that our generation will have. For instance:

1. Addition, 
2. Modification,
3. Deletion

Depending on this we should create the GoldStandard. If we add an element, then this element should be added in pairs, `aml1:Element aml2:Element 1`.

Can you try this?
The addition should be done following a distribution.

**Comment by omarrana** [comment]
close it please
