### ISSUE TITLE
Properly accomodation of the generated files

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#2]
Let us say that you have in an RDF file the different types of conflicts:

2 - Granularity
3 - Schema
- You will locate in some folder, given as a parameter, all the seeds that will be the input of your method.
- The main call will be something like new AMLGoldStandardGenerator().mainGenerator(2, 3);

For each of the identified heterogeneities(2,3) you will have a method, and for each of these you will generate 2 files as an output.

The result will be

folder _Granularity(2)_
seed1.aml
seed1-granularity1.aml
seed1-granularity2.aml

folder _Schema(3)_
seed1.aml
seed1-schema1.aml
seed1-schema2.aml

Also, we might have files containing more than one conflict.

**Comment by omarrana** [comment]
we can give as many numbers to argument and then use switch to refer to the heterogeneity
https://github.com/i40-Tools/HeterogeneityGenerator/blob/e85bbc1a1d7d43f6dcac2251dd233711c5e2a1a3/src/main/java/edu/bonn/HetrogeneityGenerator/xmlGen/AMLGoldStandardGenerator.java#L43-L109

**Comment by igrangel** [comment]
In the generation folders, there is output/seed-1/M1-Granularity, and M2. Please fix it accordingly.

**Comment by omarrana** [comment]
ok got it. thanks
