### ISSUE TITLE
Adding a flag for the random number of elements

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#24]
Would be very complicated to add a flag that sets on/off the capability of randomized the number of elements? The problem is that in the same run and, due to the randomized number of elements we can't obtain the same results for the method and sometimes we need to have a fixed number. If this is possible to do quickly we do it now, if not we do it later.

**Comment by omarrana** [comment]
close it please

**Comment by igrangel** [comment]
Could you please point to the line of code where this is solved?

**Comment by omarrana** [comment]
it is explained in readme.
Randomization can be disabled in config.ttl
