### ISSUE TITLE
Properly name of the Project

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#3]
The correct name of the Project is AMLGoldStandardGenerator. Please, rename the project in this way, as well as the packages.

**Comment by igrangel** [comment]
Update the name of the project in the description pages as well, i.e., readme.md

**Comment by igrangel** [comment]
You should rename the xmlGen as well. 
AMLGoldStandardGenerator/src/main/java/edu/bonn/AMLGoldStandardGenerator/xmlGen/

**Comment by igrangel** [comment]
In the description of the project is said "Tool to generate heterogeneity AML files for data integration."
The aim of the Tool is to generate the Gold Standard which is a bit more than the heterogeneity generation.

**Comment by igrangel** [comment]
The input file, should not be named "Integration.aml" but "seed" or something similar. 
https://github.com/i40-Tools/AMLGoldStandardGenerator/blob/master/configuration.ttl#L9

**Comment by omarrana** [comment]
hi, you forgot to press "y" after selecting the code so the URL changes, otherwise it gets replaced after new commit.

https://github.com/i40-Tools/AMLGoldStandardGenerator/blob/0fdc3e4819bdeb8347b9c7d37aada54138916c70/configuration.ttl#L9-L45

**Comment by igrangel** [comment]
Could you write the _pattern_ of how to do that?

**Comment by omarrana** [comment]
when you have selected the part of the code using shift.  Just press the key 'y' and the URL at the top would change. That URL is fixed in that commit and won't change even new commit occurs.so copy that new url and paste in issues.

**Comment by igrangel** [comment]
You are calling Heterogeneity when actually should be called Document or Files. A AML document has one or more type of Heterogeneity. Like here, https://github.com/i40-Tools/AMLGoldStandardGenerator/blob/3aabce757483db733c8c8e6cbfdff58b087fe78b/configuration.ttl#L27, please, change it
