### ISSUE TITLE
External resources should not be hard coded

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#4]
We should parametrized everything, for now, in the configuration file. 
https://github.com/i40-Tools/AMLGoldStandardGenerator/blob/master/src/main/java/edu/bonn/AMLGoldStandardGenerator/rdf/ConfigManager.java#L47

**Comment by omarrana** [comment]
https://github.com/i40-Tools/AMLGoldStandardGenerator/blob/0fdc3e4819bdeb8347b9c7d37aada54138916c70/src/main/java/edu/bonn/AMLGoldStandardGenerator/rdf/ConfigManager.java#L299-L306
