### ISSUE TITLE
Precision and recall implementation

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#6]
In order to compute [precision](https://en.wikipedia.org/wiki/Precision_and_recall#Precision) and [recal](https://en.wikipedia.org/wiki/Precision_and_recall#Recall) we should define the paralel to the _retrieved documents_ and the _relevant documents_. In our context, _documents_ are equivalent to _conflicts_. Thus, this calculation, as well as the Gold Standard itseld, should be based on the conflicts.

**Comment by igrangel** [comment]
Please, have a look at [this](https://github.com/rap1ds/information-retrieval/blob/master/src/ir_course/PrecisionRecallCalculator.java) code.

**Comment by omarrana** [comment]
What I was already working on is instead of relevant document , we can assume relevant text in a document. And how we say its relevant by looking at our Gold standard.  Then apply these known precision formula over it. However since our text is XML we also have to keep in mind other factors while comparing, the parent node , child's and it semantic in order to qualify that node as relevant.
The above code is the implementation of the formula and not the previous part.

**Comment by igrangel** [comment]
We need to focus on the conflicts. For example, we have **document A** and **document B**. Between them, we have two conflicts. A human (Gold Standard, relevant documents) is able to identify those conflicts and create a **document C** with the two conflicts solved.
A tool, can also generate **document C** but, say with only one conflict solved. So, for these types of cases we need to create our algorithm of calculation.

**Comment by igrangel** [comment]
I have seen the implementation. I still don´t understand what is for you _Relevant Text_ and _Total Text_. Looks like the calculation is ok but those concepts are not.

**Comment by omarrana** [comment]
Relevant text is the one in the gold standard I.e all the nodes.  Relevant text found is the text in generated file  I.e the nodes that qualify according to semantic and text match.
Total text is the text found in generated file which includes relevant and non relevant.

**Comment by igrangel** [comment]
I have rechecked and what we really want to compute are the conflicts, not the Text itsel.

**Comment by igrangel** [comment]
This is needed in the [AlligatorPSL](github.com/i40-Tools/Alligator-PSL) project.
