### ISSUE TITLE
The configuration file should be syntactically checked 

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#9]
For example, this https://github.com/i40-Tools/AMLGoldStandardGenerator/blob/3aabce757483db733c8c8e6cbfdff58b087fe78b/configuration.ttl#L17 is an error that should be fixed before pushed when has been validated against some RDF validator tool.

**Comment by omarrana** [comment]
ok thanks. This should not be here anyways because its defined in vocabulary folder.
